version: '2.4'

services:
  s3:
    container_name: minio
    image: harbor.difica/dockerhub-proxy/minio/minio:RELEASE.2022-01-28T02-28-16Z
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
      MINIO_PROMETHEUS_AUTH_TYPE: "public"
    volumes:
      - /minio:/data
#    command: server --address ":9099" --console-address ":9000" /data
    command: server --address 0.0.0.0:9000 --console-address ":9001" /data
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
        interval: 30s
        timeout: 20s
        retries: 3
    restart: always # necessary since it's failing to start sometimes

